import 'models.dart';

final List<Module> curriculum = [
  Module(
    id: 'dart_basics_1',
    title: 'Fundamentos de Dart',
    description: 'Aprenda a base sólida da linguagem: variáveis, constantes e lógica básica.',
    order: 1,
    lessons: [
      Lesson(
        title: 'Variáveis e Constantes',
        content: 'No Dart, usamos "var" para variáveis que mudam. Mas se o valor for fixo, prefira "final" ou "const".\n\n"const" é para valores imutáveis definidos antes do código rodar, enquanto "final" pode ser definido enquanto o app executa.',
        codeExample: 'var nome = "Dash";\nfinal data = DateTime.now();\nconst pi = 3.14;',
        relatedQuizIds: ['v1', 'v2', 'v3'],
      ),
      Lesson(
        title: 'Decisões no Código',
        content: 'Usamos "if" (se) e "else" (senão) para tomar decisões. Para comparar valores, usamos "==" (igual) ou "!=" (diferente).',
        codeExample: 'if (idade >= 18) {\n  print("Entrada liberada");\n}',
        relatedQuizIds: ['c1', 'c2', 'c3'],
      ),
      Lesson(
        title: 'Texto com Variáveis',
        content: 'A interpolação permite colocar variáveis dentro de frases usando o símbolo "\$". Fácil né?',
        codeExample: 'String pet = "Dash";\nprint("Olá, \$pet!");',
        relatedQuizIds: ['e1'],
      ),
    ],
    quizzes: [
      // VARIAVEIS
      Quiz(
        id: 'v1',
        question: 'Qual palavra-chave usamos para declarar uma variável cujo valor será definido apenas uma vez, em tempo de execução?',
        options: ['final', 'const', 'var', 'static'],
        correctAnswer: 'final',
        type: QuizType.multipleChoice,
        explanation: 'Dica: "final" é usado para valores que não mudam depois de definidos, mas podem ser calculados enquanto o programa roda.',
      ),
      Quiz(
        id: 'v2',
        question: 'Complete o código para definir uma constante que nunca mudará, nem mesmo em tempo de execução:',
        options: ['const', 'final', 'var', 'let'],
        correctAnswer: 'const',
        type: QuizType.fillInBlank,
        codeSnippet: '____ double pi = 3.1415;',
        explanation: 'Dica: "const" é usado para constantes de tempo de compilação, ou seja, valores que já sabemos antes do app rodar.',
      ),
      Quiz(
        id: 'v3',
        question: 'Se você não sabe o tipo de uma variável mas quer que o Dart o descubra sozinho, qual palavra-chave usa?',
        options: ['dynamic', 'var', 'Object', 'auto'],
        correctAnswer: 'var',
        type: QuizType.multipleChoice,
        explanation: 'Dica: O Dart usa inferência de tipo com a palavra-chave "var".',
      ),
      // CONDICIONAIS
      Quiz(
        id: 'c1',
        question: 'Qual é o resultado deste código?',
        options: ['Pode entrar', 'Proibido', 'Erro', 'Nada'],
        correctAnswer: 'Proibido',
        type: QuizType.multipleChoice,
        codeSnippet: 'int idade = 16;\nif (idade >= 18) {\n  print("Pode entrar");\n} else {\n  print("Proibido");\n}',
        explanation: 'Dica: Como 16 não é maior nem igual a 18, o código executa o bloco "else".',
      ),
      Quiz(
        id: 'c2',
        question: 'Como verificamos se duas variáveis são iguais no Dart?',
        options: ['=', '==', '===', 'equals'],
        correctAnswer: '==',
        type: QuizType.multipleChoice,
        explanation: 'Dica: Um sinal de "=" atribui valor, enquanto dois sinais "==" comparam igualdade.',
      ),
      Quiz(
        id: 'c3',
        question: 'Qual operador lógico usamos para "OU" (pelo menos uma condição verdadeira)?',
        options: ['&&', '||', '!', '??'],
        correctAnswer: '||',
        type: QuizType.multipleChoice,
        explanation: 'Dica: "||" (pipes) representa o OU lógico. Já "&&" representa o E lógico.',
      ),
      // EXPRESSOES
      Quiz(
        id: 'e1',
        question: 'Como realizamos a interpolação de uma variável dentro de uma String?',
        options: ['"Valor: {x}"', '"Valor: \$x"', '"Valor: +x"', '"Valor: (x)"'],
        correctAnswer: '"Valor: \$x"',
        type: QuizType.multipleChoice,
        explanation: 'Dica: Usamos o símbolo "\$" seguido do nome da variável para inseri-la em uma String.',
      ),
      Quiz(
        id: 'e2',
        question: 'Qual o resultado de 10 % 3?',
        options: ['3', '1', '0', '3.33'],
        correctAnswer: '1',
        type: QuizType.multipleChoice,
        explanation: 'Dica: O operador "%" (módulo) retorna o resto da divisão. 10 dividido por 3 dá 3 e sobra 1.',
      ),
      Quiz(
        id: 'e3',
        question: 'Como verificamos se uma String está vazia?',
        options: ['s.isEmpty', 's.isNull', 's.length == 0', 'As opções 1 e 3'],
        correctAnswer: 'As opções 1 e 3',
        type: QuizType.multipleChoice,
        explanation: 'Dica: Tanto "isEmpty" quanto verificar se "length == 0" funcionam no Dart.',
      ),
    ],
  ),
  Module(
    id: 'dart_logic_2',
    title: 'Coleções e Repetição',
    description: 'Entenda como lidar com listas de dados e como repetir tarefas de forma eficiente.',
    order: 2,
    lessons: [
      Lesson(
        title: 'Trabalhando com Listas',
        content: 'Listas armazenam vários itens em uma única variável. Elas são indexadas, o que significa que o primeiro item está na posição [0].',
        codeExample: 'var frutas = ["Maçã", "Uva"];\nprint(frutas[0]); // Maçã',
        relatedQuizIds: ['l1', 'l2', 'l3'],
      ),
      Lesson(
        title: 'Automação com Loops',
        content: 'Loops servem para repetir código sem precisar escrever a mesma coisa várias vezes. O "for (var item in lista)" é o seu melhor amigo.',
        codeExample: 'for (var f in frutas) {\n  print(f);\n}',
        relatedQuizIds: ['lo1', 'lo2', 'lo3'],
      ),
    ],
    quizzes: [
      // LISTAS
      Quiz(
        id: 'l1',
        question: 'Como acessamos o primeiro elemento de uma lista chamada "numeros"?',
        options: ['numeros[0]', 'numeros[1]', 'numeros.first()', 'numeros.get(0)'],
        correctAnswer: 'numeros[0]',
        type: QuizType.multipleChoice,
        explanation: 'Dica: No Dart (e na maioria das linguagens), as listas começam no índice 0.',
      ),
      Quiz(
        id: 'l2',
        question: 'Qual método usamos para adicionar um item ao final de uma lista?',
        options: ['push()', 'add()', 'insert()', 'append()'],
        correctAnswer: 'add()',
        type: QuizType.multipleChoice,
        explanation: 'Dica: O método "add" insere um novo elemento no final da List.',
      ),
      Quiz(
        id: 'l3',
        question: 'Como pegamos a quantidade de itens em uma lista?',
        options: ['list.size', 'list.length', 'list.count', 'list.amount'],
        correctAnswer: 'list.length',
        type: QuizType.multipleChoice,
        explanation: 'Dica: Diferente do Java (size), no Dart usamos a propriedade "length".',
      ),
      // LOOPS
      Quiz(
        id: 'lo1',
        question: 'Qual loop é mais indicado para percorrer todos os itens de uma lista?',
        options: ['for-in', 'while', 'if', 'repeat'],
        correctAnswer: 'for-in',
        type: QuizType.multipleChoice,
        codeSnippet: 'for (var item in lista) {\n  print(item);\n}',
        explanation: 'Dica: O "for-in" é a forma mais limpa de iterar sobre coleções.',
      ),
      Quiz(
        id: 'lo2',
        question: 'Qual comando usamos para sair imediatamente de um loop?',
        options: ['exit', 'stop', 'break', 'return'],
        correctAnswer: 'break',
        type: QuizType.multipleChoice,
        explanation: 'Dica: O "break" interrompe a execução do loop atual.',
      ),
      Quiz(
        id: 'lo3',
        question: 'O que o código abaixo imprimirá?',
        options: ['0 1 2', '1 2 3', '0 1 2 3', '3 2 1'],
        correctAnswer: '0 1 2',
        type: QuizType.multipleChoice,
        codeSnippet: 'for (int i = 0; i < 3; i++) {\n  print(i);\n}',
        explanation: 'Dica: O loop começa em 0 e vai enquanto i for menor que 3 (0, 1, 2).',
      ),
    ],
  ),
  Module(
    id: 'flutter_intro_3',
    title: 'Desconstruindo Widgets',
    description: 'Agora que você domina a lógica, vamos criar interfaces incríveis.',
    order: 3,
    lessons: [
       Lesson(
        title: 'Widgets: O Coração do Flutter',
        content: 'No Flutter, quase tudo é um Widget. O "Scaffold" é o esqueleto da sua tela.',
        codeExample: 'Scaffold(\n  appBar: AppBar(),\n  body: Center(),\n)',
        relatedQuizIds: ['f1'],
      ),
    ],
    quizzes: [
       Quiz(
        id: 'f1',
        question: 'Qual widget é a base para quase todos os layouts de tela no Material Design?',
        options: ['Container', 'Scaffold', 'App', 'Screen'],
        correctAnswer: 'Scaffold',
        type: QuizType.multipleChoice,
        explanation: 'Dica: O Scaffold fornece a estrutura básica como AppBar, Body e FloatingActionButton.',
      ),
    ],
  ),
];
